---

- name: set time zone
  timezone:
    name: '{{ system_timezone }}'
  tags:
    - timezone

# -----------------------------------------------------------------------------
# get rid of chrony
# -----------------------------------------------------------------------------

- name: remove chrony
  yum:
    pkg: chrony
    state: absent

# -----------------------------------------------------------------------------
# install ntp
# -----------------------------------------------------------------------------

- name: install ntp
  yum:
    pkg: '{{ ntp_distro_packages | join(",") }}'

- name: configure ntp
  template:
    src: '{{ ntp_template_name }}-ntp.conf.j2'
    dest: /etc/ntp.conf
    mode: 0644
    owner: root
    group: root
  register: __ntp_configuration
  tags:
    - ntp-conf

- name: enable ntpd service and assure it is started
  service:
    name: ntpd
    enabled: yes
    state: >-
      {{
        __ntp_configuration.changed |
          default(False) |
          ternary("restarted", "started")
      }}
  tags:
    - ntp-conf
    - ntp-service
    - service
    - service-ntp

...
